name: Deploy Node.js App

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u iqbalsha22 --password-stdin

      - name: Build Docker image
        run: docker build -t iqbalsha22/dockerized-image:${{ github.sha }} .

      - name: Push Docker image
        run: docker push iqbalsha22/dockerized-image:${{ github.sha }}

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: SSH into remote server and deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            docker pull iqbalsha22/dockerized-image:${{ github.sha }}
            docker stop my-container || true
            docker rm my-container || true
            docker run -d --name my-container -p 3000:3000 iqbalsha22/dockerized-image:${{ github.sha }}
